import './globals.css'
import { Montserrat } from 'next/font/google'
import Styles from './layout.module.css'
import Navbar from '@/lib/components/Navbar'
import Footer from '@/lib/components/Footer'


const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'Denys Uhrimov',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body 
      className={montserrat.className}>
        <Navbar/>
        
        {children}
        <Footer/>
        </body>
    </html>
  )
}
